"""empty message

Revision ID: 9850a1e3b1cf
Revises: a44dd4ba596a
Create Date: 2025-05-22 03:00:34.657201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9850a1e3b1cf'
down_revision: Union[str, None] = 'a44dd4ba596a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('advertisements', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('advertisements', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False))
    op.add_column('advertisements', sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('advertisements', sa.Column('is_price_negotiable', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('advertisements', 'is_price_negotiable')
    op.drop_column('advertisements', 'price')
    op.drop_column('advertisements', 'description')
    op.drop_column('advertisements', 'title')
    # ### end Alembic commands ###
